# Core Jekyll Configuration
locale                : 'en'
source                : 'jekyll'
destination           : 'html'
url                   : 'https://sjmst5.github.io'
enforce_ssl           : 'sjmst5.github.io'
permalink             : '/articles/:title'
include               : ['_pages']
plugins               : []
